name: Publish

on:
  release:
    types: [published]

jobs:
  npmjs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install deps and build (with cache)
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 7.1.3
          run_install: true

      - name: Build
        run: pnpm build

      - name: Prepare Pack
        run: cp package.json README.md dist/

      - uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/

      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

